include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_print
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_const_declarations
    - avoid_unnecessary_containers
    - use_key_in_widget_constructors
    - prefer_final_fields
    - prefer_final_locals
    - unnecessary_string_interpolations
    - unnecessary_string_escapes
    - avoid_function_literals_in_foreach_calls
    - prefer_is_empty
    - prefer_is_not_empty
    - avoid_single_cascade_in_expression_statements
    - prefer_null_aware_operators
    - prefer_conditional_assignment

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated/**"